---
- hosts: 127.0.0.1
  roles:
    - bt5e.docker_ce
    - bt5e.docker_compose
    - { role: bt5e.docker-non-root-user, non_root_docker_users: vagrant }
    - bt5e.kubectl
    - bt5e.k8s_helm

  tasks:
    - name: Install packages via yum
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - "@Development tools"
        - "python-devel"
        - "python-pip"
      become: yes

    - name: Install python packages
      pip:
        name: "{{ item.name }}"
        version: "{{ item.version }}"
      with_items:
        - { name: pip, version: "18.1" }
        - { name: jinja2, version: "2.10" }
      become: yes
